const mongoose = require('mongoose');
const Article = require('./models/Article');

const categories = ["Technology", "Business", "Sports", "Health", "Entertainment", "Science", "Politics", "International"];

const seedArticles = [
    // Technology
    { title: "AI Surpasses Human Performance in Complex Reasoning Tasks", category: "Technology", author: "SmartNews Editorial", location: "San Francisco", content: "Artificial intelligence has reached a new milestone as leading models demonstrate superhuman performance on complex reasoning benchmarks. Researchers at top labs confirmed that the latest generation of large language models can now solve graduate-level math problems, write production-quality code, and analyze scientific papers with greater accuracy than human experts. This breakthrough raises important questions about the future of work and education, as industries scramble to integrate these powerful new tools into their workflows. Experts predict that within the next two years, AI assistants will become standard in every professional environment.", isToday: true },
    { title: "Quantum Computing Breaks 1000-Qubit Barrier", category: "Technology", author: "SmartNews Editorial", location: "Tokyo", content: "In a landmark achievement for quantum computing, researchers have successfully built and operated a quantum processor with over 1000 stable qubits. This milestone brings quantum advantage closer to reality for practical applications like drug discovery, materials science, and cryptography. The team used a novel error-correction technique that dramatically reduces decoherence, allowing quantum states to persist long enough for meaningful computation. Industry analysts expect commercial quantum computing services to become available within the next three to five years." },
    { title: "The Rise of Edge Computing: Processing Data Where It Matters", category: "Technology", author: "SmartNews Editorial", location: "Berlin", content: "Edge computing is transforming how businesses process data by bringing computation closer to the source. Instead of sending everything to centralized cloud servers, edge devices handle processing locally, reducing latency and bandwidth costs. This shift is particularly impactful for autonomous vehicles, smart factories, and healthcare monitoring systems that require real-time decision-making. Major cloud providers are now offering edge computing solutions, and the market is expected to grow to $61 billion by 2028." },
    { title: "Cybersecurity in 2026: Zero Trust Architecture Becomes Standard", category: "Technology", author: "SmartNews Editorial", location: "London", content: "Organizations worldwide are rapidly adopting zero trust security frameworks as cyber threats continue to evolve. The traditional perimeter-based security model has proven inadequate against sophisticated attacks, leading companies to verify every user and device regardless of their location on the network. Recent high-profile breaches have accelerated this transition, with government agencies now mandating zero trust compliance for all contractors and partners." },
    { title: "5G Networks Enable Smart City Infrastructure Revolution", category: "Technology", author: "SmartNews Editorial", location: "Seoul", content: "Fifth-generation wireless networks are finally delivering on their promise of enabling truly smart cities. With ultra-low latency and massive device connectivity, municipalities are deploying intelligent traffic management, environmental monitoring, and public safety systems at unprecedented scale. Seoul has become a model for other cities, with its comprehensive 5G-powered infrastructure reducing traffic congestion by 30% and emergency response times by 45%." },

    // Business
    { title: "Global Startup Funding Rebounds to Record Highs in Q1 2026", category: "Business", author: "SmartNews Editorial", location: "New York", content: "Venture capital investment has surged to unprecedented levels in the first quarter of 2026, with global startup funding reaching $150 billion. AI-focused companies captured the lion's share of investment, but climate tech and biotech startups also saw significant increases. The rebound follows two years of cautious spending, as investors gain confidence in the economic outlook and the transformative potential of emerging technologies. Late-stage valuations have recovered to 2021 peaks, though investors are now demanding clearer paths to profitability.", isToday: true },
    { title: "Remote Work Revolution: Companies Embrace Fully Distributed Teams", category: "Business", author: "SmartNews Editorial", location: "Austin", content: "A growing number of Fortune 500 companies are eliminating traditional office requirements entirely, embracing fully distributed workforce models. This shift has been driven by data showing that remote workers are often more productive and satisfied than their in-office counterparts. Companies report savings of up to 40% on real estate costs, while employees benefit from improved work-life balance and the freedom to live anywhere. The trend is reshaping commercial real estate markets and creating new opportunities for smaller cities." },
    { title: "Sustainable Business Practices Now Drive Consumer Purchasing Decisions", category: "Business", author: "SmartNews Editorial", location: "Amsterdam", content: "A comprehensive global survey reveals that 73% of consumers now actively consider environmental sustainability when making purchasing decisions. Brands that have invested in transparent supply chains, renewable energy, and circular economy practices are seeing measurable revenue increases. The shift is forcing traditional companies to accelerate their sustainability transformations or risk losing market share to more environmentally conscious competitors." },
    { title: "The Creator Economy Crosses $500 Billion Valuation", category: "Business", author: "SmartNews Editorial", location: "Los Angeles", content: "The creator economy has officially crossed the half-trillion dollar mark, driven by explosive growth in digital content, online education, and direct-to-consumer commerce. Individual creators are building media empires that rival traditional companies, with top earners generating hundreds of millions in annual revenue. Platforms are competing fiercely for creator talent, offering increasingly generous revenue-sharing deals and sophisticated tools for audience engagement and monetization." },
    { title: "Central Banks Worldwide Pilot Digital Currencies", category: "Business", author: "SmartNews Editorial", location: "Singapore", content: "Over 30 central banks are now actively piloting digital currency systems, marking a fundamental shift in global monetary infrastructure. These Central Bank Digital Currencies promise faster cross-border transactions, reduced costs for the unbanked, and more effective monetary policy implementation. However, privacy advocates raise concerns about government surveillance capabilities, while commercial banks worry about disintermediation." },

    // Sports
    { title: "Historic World Cup Qualifier Sees Underdog Nations Rise", category: "Sports", author: "SmartNews Editorial", location: "Doha", content: "The latest round of World Cup qualifiers has produced stunning upsets as several traditionally weaker footballing nations have defeated established powerhouses. The results reflect the growing globalization of football talent development and the increasing competitiveness of international football. Advanced analytics and sports science have helped smaller nations optimize their limited resources, creating more tactically sophisticated teams that can compete with anyone on their day.", isToday: true },
    { title: "Olympic Committee Announces Revolutionary Format Changes for 2028", category: "Sports", author: "SmartNews Editorial", location: "Lausanne", content: "The International Olympic Committee has unveiled sweeping changes to the 2028 Los Angeles Games format, including the addition of esports as a medal event and significant modifications to existing sports schedules. The changes aim to attract younger audiences while maintaining the Olympic tradition. Cricket and flag football will also make their Olympic debuts, reflecting the growing global appeal of these sports." },
    { title: "Tennis Grand Slam Records Shattered by New Generation", category: "Sports", author: "SmartNews Editorial", location: "Melbourne", content: "A new generation of tennis players is rewriting the record books, with three players under 22 winning Grand Slam titles in the past year. The young stars combine incredible athleticism with sophisticated tactical awareness, often using AI-powered coaching tools to analyze opponents and optimize their game. The changing of the guard has energized tennis audiences worldwide, with viewership numbers reaching all-time highs." },
    { title: "Formula 1 Introduces Sustainable Fuel Mandate Starting 2027", category: "Sports", author: "SmartNews Editorial", location: "Monaco", content: "Formula 1 has announced that all teams must use 100% sustainable fuel beginning in the 2027 season, marking a historic commitment to environmental responsibility in motorsport. The mandate has sparked intense competition among fuel suppliers and engine manufacturers to develop high-performance sustainable alternatives. Teams are already testing prototype fuels that promise comparable power output while dramatically reducing carbon emissions." },
    { title: "Cricket's Global Expansion Reaches New Markets", category: "Sports", author: "SmartNews Editorial", location: "Mumbai", content: "Cricket continues its rapid global expansion with new professional leagues launching in the United States, Germany, and Japan. The sport's shorter formats, particularly T20, have proven extremely popular with new audiences who appreciate the fast-paced, high-scoring action. Broadcasting deals worth billions of dollars are fueling the expansion, while franchise ownership groups from football and basketball are investing heavily in cricket teams." },

    // Health
    { title: "Breakthrough Gene Therapy Reverses Age-Related Vision Loss", category: "Health", author: "SmartNews Editorial", location: "Boston", content: "A revolutionary gene therapy treatment has successfully restored vision in patients with age-related macular degeneration, the leading cause of blindness in older adults. The one-time injection delivers functional copies of a protective gene directly to retinal cells, halting and even reversing damage. Clinical trials showed that 87% of patients experienced significant vision improvement within six months. The treatment is expected to receive regulatory approval by early 2027.", isToday: true },
    { title: "Mental Health Apps Show Clinical Effectiveness in Large-Scale Study", category: "Health", author: "SmartNews Editorial", location: "Stockholm", content: "A comprehensive study involving over 50,000 participants has demonstrated that AI-powered mental health applications can be as effective as traditional therapy for mild to moderate anxiety and depression. The apps use cognitive behavioral therapy techniques adapted for digital delivery, with personalized interventions based on user behavior patterns. Researchers emphasize that the apps complement rather than replace human therapists, particularly for severe conditions." },
    { title: "New Vaccine Technology Promises Universal Flu Protection", category: "Health", author: "SmartNews Editorial", location: "Geneva", content: "Scientists have developed a next-generation vaccine platform that could provide broad protection against all influenza strains, eliminating the need for annual flu shots. The vaccine targets conserved regions of the virus that remain consistent across mutations, training the immune system to recognize any flu variant. Phase 2 clinical trials have shown promising results, with participants developing robust immunity that lasted over two years." },
    { title: "Wearable Health Monitors Detect Disease Before Symptoms Appear", category: "Health", author: "SmartNews Editorial", location: "Cupertino", content: "Advanced wearable devices are now capable of detecting early signs of several serious diseases, including diabetes, cardiac arrhythmias, and respiratory infections, days before symptoms manifest. Machine learning algorithms analyze continuous biometric data streams to identify subtle patterns that indicate disease onset. Early detection has been shown to improve treatment outcomes by up to 60% and reduce healthcare costs significantly." },
    { title: "Personalized Nutrition Plans Based on Gut Microbiome Analysis", category: "Health", author: "SmartNews Editorial", location: "Tel Aviv", content: "Personalized nutrition is entering the mainstream as affordable gut microbiome testing becomes widely available. By analyzing the trillions of bacteria in an individual's digestive system, nutritionists can now create highly tailored dietary recommendations that optimize health outcomes for each person. Studies show that microbiome-based diets lead to better weight management, improved energy levels, and reduced inflammation compared to generic dietary guidelines." },

    // Entertainment
    { title: "Streaming Wars Intensify as Interactive Content Takes Center Stage", category: "Entertainment", author: "SmartNews Editorial", location: "Hollywood", content: "Major streaming platforms are investing heavily in interactive content that allows viewers to influence storylines in real-time. This new format blurs the line between traditional television and gaming, creating deeply engaging experiences that dramatically increase viewer retention. The technology uses AI to generate branching narratives that adapt to audience choices, with some shows offering thousands of possible story paths.", isToday: true },
    { title: "Virtual Concert Platforms Generate $2 Billion in Revenue", category: "Entertainment", author: "SmartNews Editorial", location: "Nashville", content: "Virtual and augmented reality concert experiences have become a major entertainment category, generating over $2 billion in revenue in the past year. Artists can now perform for millions of simultaneous attendees in immersive digital venues that offer experiences impossible in physical spaces. The technology has democratized access to live music, with fans in remote areas enjoying front-row experiences from their homes." },
    { title: "AI-Generated Music Sparks Creative Renaissance and Legal Debates", category: "Entertainment", author: "SmartNews Editorial", location: "London", content: "The proliferation of AI music generation tools has sparked both a creative renaissance and heated legal debates about copyright and artistic authenticity. Independent musicians are using AI as a collaborative tool to expand their creative capabilities, while major labels grapple with questions about ownership and compensation. New legislation is being proposed in several countries to establish clear frameworks for AI-assisted creative works." },
    { title: "Gaming Industry Surpasses Film and Music Combined in Revenue", category: "Entertainment", author: "SmartNews Editorial", location: "Tokyo", content: "The global gaming industry has reached $300 billion in annual revenue, officially surpassing the combined revenues of the film and music industries. Mobile gaming continues to drive the majority of growth, but console and PC gaming are also seeing strong increases. The rise of cloud gaming services has eliminated hardware barriers to entry, making premium gaming experiences accessible to billions of new players worldwide." },
    { title: "Immersive Theater Experiences Transform Live Entertainment", category: "Entertainment", author: "SmartNews Editorial", location: "New York", content: "Immersive theater productions are revolutionizing live entertainment by placing audiences directly inside the narrative. These experiences combine theatrical performance, interactive technology, and elaborate set design to create deeply personal and memorable events. Ticket prices for premium immersive experiences can exceed $500, yet demand consistently outstrips supply, with some shows sold out months in advance." },

    // Science
    { title: "Mars Soil Analysis Reveals Evidence of Ancient Microbial Life", category: "Science", author: "SmartNews Editorial", location: "Houston", content: "NASA's Perseverance rover has discovered compelling chemical signatures in Martian soil samples that strongly suggest the presence of ancient microbial life. The findings, confirmed by independent analysis at multiple laboratories, represent one of the most significant scientific discoveries in human history. The organic compounds found are consistent with bacterial metabolism and cannot be easily explained by non-biological processes. The scientific community is calling for accelerated efforts to return the samples to Earth for more detailed study.", isToday: true },
    { title: "Nuclear Fusion Experiment Achieves Net Energy Gain for Extended Period", category: "Science", author: "SmartNews Editorial", location: "Oxford", content: "Scientists at a European research facility have achieved a sustained nuclear fusion reaction that produced more energy than it consumed for a record-breaking 15 minutes. This milestone brings the dream of virtually unlimited clean energy significantly closer to reality. The experiment used an advanced tokamak design with superconducting magnets that can maintain the extreme temperatures and pressures needed for fusion. Commercial fusion power plants could be operational within 15 years." },
    { title: "Deep Ocean Exploration Discovers New Ecosystem at Record Depth", category: "Science", author: "SmartNews Editorial", location: "Monterey", content: "Marine scientists have discovered a previously unknown ecosystem thriving at the deepest point ever explored in the ocean. The ecosystem, found in an abyssal trench at nearly 12,000 meters below sea level, contains dozens of new species that have evolved unique adaptations to survive extreme pressure, complete darkness, and near-freezing temperatures. The discovery challenges our understanding of the limits of life and has implications for astrobiology." },
    { title: "CRISPR Gene Editing Successfully Treats Sickle Cell Disease", category: "Science", author: "SmartNews Editorial", location: "Atlanta", content: "A landmark clinical trial has demonstrated that CRISPR-based gene editing can effectively cure sickle cell disease in the majority of patients. The treatment modifies patients' own stem cells to produce functional hemoglobin, eliminating the painful crises and organ damage associated with the disease. All 45 patients in the trial have been symptom-free for over a year, with their modified cells continuing to produce healthy red blood cells." },
    { title: "Astronomers Map Most Detailed 3D Structure of the Universe", category: "Science", author: "SmartNews Editorial", location: "Pasadena", content: "Using data from next-generation space telescopes, astronomers have created the most detailed three-dimensional map of the observable universe ever produced. The map reveals the cosmic web of dark matter filaments connecting galaxy clusters across billions of light-years, providing unprecedented insights into the large-scale structure of the cosmos. The data is helping scientists refine models of dark energy and understand how the universe's expansion has changed over time." },

    // Politics
    { title: "Historic Climate Agreement Commits 190 Nations to Net-Zero by 2045", category: "Politics", author: "SmartNews Editorial", location: "Paris", content: "In a landmark diplomatic achievement, 190 nations have signed a binding agreement to achieve net-zero carbon emissions by 2045, five years ahead of previous targets. The agreement includes enforcement mechanisms and financial commitments from developed nations to support developing countries in their transition to clean energy. Critics argue the targets are still insufficient to prevent the worst effects of climate change, while supporters celebrate the unprecedented level of global cooperation.", isToday: true },
    { title: "Digital Voting Systems Gain Traction in Democratic Elections", category: "Politics", author: "SmartNews Editorial", location: "Tallinn", content: "Several countries are expanding their use of digital voting systems after Estonia's two-decade success with internet-based elections. The systems use blockchain technology and advanced encryption to ensure vote integrity while dramatically increasing voter participation. Turnout in countries that have adopted digital voting has increased by an average of 15 percentage points, particularly among younger voters. However, cybersecurity experts continue to debate the risks." },
    { title: "Global Tax Reform Agreement Targets Corporate Tax Havens", category: "Politics", author: "SmartNews Editorial", location: "Brussels", content: "A landmark international tax reform agreement has established a global minimum corporate tax rate of 15% and new rules to ensure multinational corporations pay taxes where they generate revenue. The agreement targets traditional tax haven jurisdictions and is expected to generate an additional $220 billion in annual tax revenue worldwide. Technology companies and pharmaceutical firms will see the most significant impact from the new rules." },
    { title: "Universal Basic Income Pilots Report Positive Economic Outcomes", category: "Politics", author: "SmartNews Editorial", location: "Helsinki", content: "Multiple universal basic income pilot programs around the world are reporting overwhelmingly positive results. Recipients showed improved mental health, increased entrepreneurship, and continued workforce participation, contrary to critics' predictions. The programs provided monthly payments ranging from $500 to $1,200 to randomly selected citizens without conditions. Policymakers in several countries are now considering national-scale UBI implementation." },
    { title: "International Space Governance Framework Proposed at UN Summit", category: "Politics", author: "SmartNews Editorial", location: "Vienna", content: "The United Nations has proposed a comprehensive framework for governing commercial activities in outer space, addressing growing concerns about satellite congestion, space debris, and resource extraction on celestial bodies. The framework establishes licensing requirements for commercial space operations, environmental standards for orbital debris mitigation, and guidelines for the equitable sharing of space-derived resources. Major spacefaring nations have expressed cautious support for the initiative." },

    // International
    { title: "Global Supply Chain Restructuring Accelerates Amid Geopolitical Shifts", category: "International", author: "SmartNews Editorial", location: "Shanghai", content: "Major corporations are dramatically restructuring their global supply chains in response to ongoing geopolitical tensions and the lessons learned from recent disruptions. The trend toward nearshoring and friend-shoring is creating new manufacturing hubs in Southeast Asia, Latin America, and Eastern Europe. While the transition increases costs in the short term, companies report greater resilience and reduced risk from their diversified supply networks.", isToday: true },
    { title: "African Continental Free Trade Area Boosts Intra-African Commerce", category: "International", author: "SmartNews Editorial", location: "Nairobi", content: "The African Continental Free Trade Area is delivering impressive results two years after full implementation, with intra-African trade increasing by 35%. The agreement, which covers 1.3 billion people and creates the world's largest free trade zone by number of participating countries, is accelerating industrialization and creating millions of new jobs across the continent. Digital payment systems and improved logistics infrastructure have been crucial enablers of the trade increase." },
    { title: "Arctic Shipping Routes Transform Global Trade Patterns", category: "International", author: "SmartNews Editorial", location: "Oslo", content: "The opening of Arctic shipping routes due to melting sea ice is fundamentally altering global trade patterns, reducing transit times between Asia and Europe by up to 40%. The Northern Sea Route and Northwest Passage are seeing exponential increases in commercial traffic, creating new economic opportunities for Arctic nations while raising serious environmental concerns. International negotiations over Arctic governance and environmental protection are intensifying." },
    { title: "Global Refugee Crisis Prompts Innovative International Cooperation", category: "International", author: "SmartNews Editorial", location: "Geneva", content: "With the global refugee population exceeding 120 million, an unprecedented international cooperation framework has been established to provide more effective support and integration opportunities. The initiative combines financial commitments from wealthy nations with skills-based immigration programs that match refugees with labor market needs in host countries. Early results show that the approach benefits both refugees and host communities economically." },
    { title: "Undersea Cable Network Expansion Bridges Digital Divide", category: "International", author: "SmartNews Editorial", location: "Lisbon", content: "A massive international investment in undersea fiber optic cables is dramatically expanding internet connectivity in previously underserved regions. New cable systems connecting Africa, South Asia, and Pacific Island nations are delivering broadband speeds that were previously unavailable, opening opportunities for education, commerce, and governance. The $50 billion infrastructure project involves cooperation between governments, tech companies, and international development organizations." }
];

async function seedDB() {
    try {
        await mongoose.connect("mongodb://127.0.0.1:27017/SmartNewsDB");
        console.log("Connected to MongoDB for seeding...");

        const count = await Article.countDocuments();
        if (count > 0) {
            console.log(`Database already has ${count} articles. Clearing and reseeding...`);
            await Article.deleteMany({});
        }

        await Article.insertMany(seedArticles);
        console.log(`✅ Seeded ${seedArticles.length} articles (${categories.length} categories × 5 each)`);

        await mongoose.disconnect();
        console.log("Done. Disconnected.");
        process.exit(0);
    } catch (err) {
        console.error("Seeding failed:", err);
        process.exit(1);
    }
}

seedDB();
